######################################################################
# Automatically generated by qmake (3.0) Fri Mar 12 19:07:30 2021
######################################################################

QT += core gui widgets

TEMPLATE = app
TARGET = OrganUI
INCLUDEPATH += .

# Input
HEADERS += dialog.h
SOURCES += dialog.cpp main.cpp
